rec::robotino::api2 C++ interface: rec::robotino::api2::OmniDriveModel Class Reference
rec::robotino::api2::OmniDriveModel Class Reference
Project single motor speeds to velocity vector and vice versa.
#include <OmniDriveModel.h>
Public Member Functions
void setRb (double rb)
void setRw (double rw)
void setGear (double gear)
double rb () const
double rw () const
double gear () const
void project (float *m1, float *m2, float *m3, float vx, float vy, float omega) const
void unproject (float *vx, float *vy, float *omega, float m1, float m2, float m3) const
Detailed Description
Project single motor speeds to velocity vector and vice versa.
Member Function Documentation
gear()
double rec::robotino::api2::OmniDriveModel::gear () const inline
Returns
gear.
Referenced by setGear().
project()
void rec::robotino::api2::OmniDriveModel::project (float * m1, float * m2, float * m3, float vx, float vy, float omega) const inline
Project the velocity of the robot in cartesian coordinates to single motor speeds.
Parameters
m1 The resulting speed of motor 1 in rpm
m2 The resulting speed of motor 2 in rpm
m3 The resulting speed of motor 3 in rpm
vx Velocity in x-direction in m/s
vy Velocity in y-direction in m/s
omega Angular velocity in rad/s
Exceptions
RobotinoException if no valid drive layout parameters are available.
Remarks
This function is thread save
rb()
double rec::robotino::api2::OmniDriveModel::rb () const inline
Returns
Distance from robot center to wheel center in m.
Referenced by setRb().
rw()
double rec::robotino::api2::OmniDriveModel::rw () const inline
Returns
Radius of the wheels in m.
Referenced by setRw().
setGear()
void rec::robotino::api2::OmniDriveModel::setGear (double gear) inline
Sets the gear.
Parameters
gear Gear
References gear().
setRb()
void rec::robotino::api2::OmniDriveModel::setRb (double rb) inline
Sets the distance from robot center to wheel center.
Parameters
rb Distance from robot center to wheel center in m.
References rb().
setRw()
void rec::robotino::api2::OmniDriveModel::setRw (double rw) inline
Sets the radius of the wheels.
Parameters
rw Radius of the wheels in m.
References rw().
unproject()
void rec::robotino::api2::OmniDriveModel::unproject (float * vx, float * vy, float * omega, float m1, float m2, float m3) const inline
Project single motor speeds to velocity in cartesian coordinates.
Parameters
vx The resulting speed in x-direction in m/s
vy The resulting speed in y-direction in m/s
omega The resulting angular velocity in rad/s
m1 Speed of motor 1 in rpm
m2 Speed of motor 2 in rpm
m3 Speed of motor 3 in rpm
Exceptions
RobotinoException if no valid drive layout parameters are available.
Remarks
This function is thread save
The documentation for this class was generated from the following file:
/home/verbeek/srcs/openrobotino/api2/lib/rec/robotino/api2/OmniDriveModel.h