rec::robotino::api2 C++ interface: rec::robotino::api2::LaserRangeFinderReadings Class Reference
rec::robotino::api2::LaserRangeFinderReadings Class Reference
Sensor readings of Robotino's (optional) laser rangefinder.
#include <LaserRangeFinderReadings.h>
Public Member Functions
LaserRangeFinderReadings ()
LaserRangeFinderReadings (const LaserRangeFinderReadings &other)
~LaserRangeFinderReadings ()
LaserRangeFinderReadings & operator= (const LaserRangeFinderReadings &other)
const char * frame_id () const
void set_frame_id (const char *frame_id)
void ranges (const float **readings, unsigned int *rangesSize=NULL) const
void setRanges (const float *ranges, unsigned int rangesSize)
unsigned int numRanges () const
void clearRanges ()
void intensities (const float **readings, unsigned int *intensitiesSize=NULL) const
void setIntensities (const float *intensities, unsigned int intensitiesSize)
unsigned int numIntensities () const
void clearIntensities ()
Public Attributes
unsigned int seq
unsigned int stamp
float angle_min
float angle_max
float angle_increment
float time_increment
float scan_time
float range_min
float range_max
Detailed Description
Sensor readings of Robotino's (optional) laser rangefinder.
Constructor & Destructor Documentation
LaserRangeFinderReadings() [1/2]
rec::robotino::api2::LaserRangeFinderReadings::LaserRangeFinderReadings () inline
Constructs an empty LaserRangeFinderReadings instance.
LaserRangeFinderReadings() [2/2]
rec::robotino::api2::LaserRangeFinderReadings::LaserRangeFinderReadings (const LaserRangeFinderReadings & other) inline
Copies an existing LaserRangeFinderReadings instance.
References set_frame_id(), setIntensities(), and setRanges().
~LaserRangeFinderReadings()
rec::robotino::api2::LaserRangeFinderReadings::~LaserRangeFinderReadings () inline
Destructor
Member Function Documentation
clearIntensities()
void rec::robotino::api2::LaserRangeFinderReadings::clearIntensities () inline
Clears the intensity data.
clearRanges()
void rec::robotino::api2::LaserRangeFinderReadings::clearRanges () inline
Clears the range data.
frame_id()
const char* rec::robotino::api2::LaserRangeFinderReadings::frame_id () const inline
Returns
The frame id.
intensities()
void rec::robotino::api2::LaserRangeFinderReadings::intensities (const float ** readings, unsigned int * intensitiesSize = NULL) const inline
Retrieves the intensity array.
Parameters
readings Array of intensities.
intensitiesSize Number of intensities.
numIntensities()
unsigned int rec::robotino::api2::LaserRangeFinderReadings::numIntensities () const inline
Returns
Number of intensities.
numRanges()
unsigned int rec::robotino::api2::LaserRangeFinderReadings::numRanges () const inline
Returns
Number of ranges.
operator=()
LaserRangeFinderReadings& rec::robotino::api2::LaserRangeFinderReadings::operator= (const LaserRangeFinderReadings & other) inline
Copies an existing LaserRangeFinderReadings instance.
References angle_increment, angle_max, angle_min, range_max, range_min, seq, set_frame_id(), setIntensities(), setRanges(), stamp, and time_increment.
ranges()
void rec::robotino::api2::LaserRangeFinderReadings::ranges (const float ** readings, unsigned int * rangesSize = NULL) const inline
Retrieves the range array.
Parameters
readings Array of ranges.
rangesSize Number of ranges.
set_frame_id()
void rec::robotino::api2::LaserRangeFinderReadings::set_frame_id (const char * frame_id) inline
Sets the frame id.
Parameters
frame_id The frame id.
Referenced by LaserRangeFinderReadings(), and operator=().
setIntensities()
void rec::robotino::api2::LaserRangeFinderReadings::setIntensities (const float * intensities, unsigned int intensitiesSize) inline
Sets the intensity array.
Parameters
intensities Array of intensities.
intensitiesSize Number of intensities.
Referenced by LaserRangeFinderReadings(), and operator=().
setRanges()
void rec::robotino::api2::LaserRangeFinderReadings::setRanges (const float * ranges, unsigned int rangesSize) inline
Sets the range array.
Parameters
ranges Array of ranges.
rangesSize Number of ranges.
Referenced by LaserRangeFinderReadings(), and operator=().
Member Data Documentation
angle_increment
float rec::robotino::api2::LaserRangeFinderReadings::angle_increment
Angle increment
Referenced by operator=().
angle_max
float rec::robotino::api2::LaserRangeFinderReadings::angle_max
Maximum angle
Referenced by operator=().
angle_min
float rec::robotino::api2::LaserRangeFinderReadings::angle_min
Minimum angle
Referenced by operator=().
range_max
float rec::robotino::api2::LaserRangeFinderReadings::range_max
Maximum range
Referenced by operator=().
range_min
float rec::robotino::api2::LaserRangeFinderReadings::range_min
Minimum range
Referenced by operator=().
scan_time
float rec::robotino::api2::LaserRangeFinderReadings::scan_time
Scan time
seq
unsigned int rec::robotino::api2::LaserRangeFinderReadings::seq
Sequence number
Referenced by operator=().
stamp
unsigned int rec::robotino::api2::LaserRangeFinderReadings::stamp
Time stamp
Referenced by operator=().
time_increment
float rec::robotino::api2::LaserRangeFinderReadings::time_increment
Time increment
Referenced by operator=().
The documentation for this class was generated from the following file:
/home/verbeek/srcs/openrobotino/api2/lib/rec/robotino/api2/LaserRangeFinderReadings.h