rec::robotino::api2 C++ interface: rec::robotino::api2::CameraFormat Class Reference
rec::robotino::api2::CameraFormat Class Reference
Camera format description.
#include <CameraFormat.h>
Public Member Functions
CameraFormat ()
CameraFormat (unsigned int width_, unsigned int height_, const char *name)
CameraFormat (const CameraFormat &other)
virtual ~CameraFormat ()
CameraFormat & operator= (const CameraFormat &other)
void setName (const char *str)
const char * name () const
Public Attributes
unsigned int width
unsigned int height
Detailed Description
Camera format description.
Constructor & Destructor Documentation
CameraFormat() [1/3]
rec::robotino::api2::CameraFormat::CameraFormat () inline
Constructs a camera format description with empty name and size 0.
CameraFormat() [2/3]
rec::robotino::api2::CameraFormat::CameraFormat (unsigned int width_, unsigned int height_, const char * name) inline
Constructs a camera format description.
Parameters
width_ Image width.
height_ Image height.
name Description name.
References setName().
CameraFormat() [3/3]
rec::robotino::api2::CameraFormat::CameraFormat (const CameraFormat & other) inline
Copys an existing camera format description.
Parameters
other Existing description to copy.
References setName().
~CameraFormat()
virtual rec::robotino::api2::CameraFormat::~CameraFormat () inline virtual
Destructor.
Member Function Documentation
name()
const char* rec::robotino::api2::CameraFormat::name () const inline
Read the format name
Returns
Format name
operator=()
CameraFormat& rec::robotino::api2::CameraFormat::operator= (const CameraFormat & other) inline
Copys an existing camera format description.
Parameters
other Existing description to copy.
References height, setName(), and width.
setName()
void rec::robotino::api2::CameraFormat::setName (const char * str) inline
Set the format name
Parameters
str The name like "mjpeg", "yuyv" ...
Referenced by CameraFormat(), and operator=().
Member Data Documentation
height
unsigned int rec::robotino::api2::CameraFormat::height
Image height in pixel
Referenced by operator=().
width
unsigned int rec::robotino::api2::CameraFormat::width
Image width in pixel
Referenced by operator=().
The documentation for this class was generated from the following file:
/home/verbeek/srcs/openrobotino/api2/lib/rec/robotino/api2/CameraFormat.h